# Generated by Django 4.2.7 on 2025-11-23 18:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('preferred_fuel', models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=20)),
                ('preferred_transmission', models.CharField(blank=True, choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription_preference', models.CharField(choices=[('achat', 'Achat'), ('lld', 'Location Longue Durée'), ('abonnement', 'Abonnement'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('loyalty_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiée'), ('in_progress', 'En cours'), ('pending_approval', "En attente d'approbation"), ('concluded', 'Conclue'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='initiated', max_length=20)),
                ('negotiation_rounds', models.IntegerField(default=0)),
                ('max_rounds', models.IntegerField(default=10)),
                ('trade_in_offered_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margin_achieved', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chosen_offer_type', models.CharField(blank=True, choices=[('achat', 'Achat'), ('lld', 'Location Longue Durée'), ('abonnement', 'Abonnement'), ('flexible', 'Flexible')], max_length=20, null=True)),
                ('agent_reasoning', models.JSONField(blank=True, default=dict)),
                ('market_analysis', models.JSONField(blank=True, default=dict)),
                ('negotiation_history', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='negotiation.client')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('version', models.CharField(max_length=100)),
                ('mileage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=20)),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20)),
                ('power_hp', models.IntegerField()),
                ('engine_cc', models.IntegerField()),
                ('original_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_market_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_trade_in_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('moyen', 'Moyen'), ('acceptable', 'Acceptable')], max_length=20)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('achat', 'Achat'), ('lld', 'Location Longue Durée'), ('abonnement', 'Abonnement')], max_length=20)),
                ('trade_in_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duration_months', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(84)])),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_months', models.IntegerField(default=12)),
                ('maintenance_included', models.BooleanField(default=False)),
                ('roadside_assistance', models.BooleanField(default=False)),
                ('insurance_included', models.BooleanField(default=False)),
                ('justification', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('offer_status', models.CharField(choices=[('proposed', 'Proposée'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('negotiating', 'En négociation')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='negotiation.negotiation')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negotiation.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('agent_proposal', models.JSONField()),
                ('agent_reasoning', models.TextField()),
                ('client_feedback', models.TextField(blank=True, null=True)),
                ('client_counter_proposal', models.JSONField(blank=True, null=True)),
                ('round_status', models.CharField(choices=[('ongoing', 'En cours'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('counter', 'Contre-proposition')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('negotiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='negotiation.negotiation')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.AddField(
            model_name='negotiation',
            name='target_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_negotiations', to='negotiation.vehicle'),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='trade_in_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_negotiations', to='negotiation.vehicle'),
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage_average', models.IntegerField()),
                ('listings_count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('make', 'model', 'year', 'fuel_type')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='trade_in_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_by', to='negotiation.vehicle'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
